theme: minima
title: India
author: niveshmahajan
email: niveshmahajan8@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  India gave "zero" to the world
# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage
